FROM golang:1.21 AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o webserver

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/webserver .
COPY --from=builder /app/index.html .

EXPOSE 8080

CMD ["./webserver"]